services:
  postgres:
    image: postgres:latest
    container_name: discordlite-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: discordlite
      POSTGRES_PASSWORD: discordlite123
      POSTGRES_DB: discordlite
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: pg_data
        target: /var/lib/postgresql/18/docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U discordlite -d discordlite"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - discordlite-net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: discordlite-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_REPLACE_SERVERS_ON_STARTUP: "True"
    ports:
      - "5050:80"
    volumes:
      - type: volume
        source: pgadmin_data
        target: /var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - discordlite-net
  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: discordlite
      MINIO_ROOT_PASSWORD: local-minio-password
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - discordlite-net
         
  

volumes:
  pg_data:
  pgadmin_data:
  minio_data:

networks:
  discordlite-net:
    driver: bridge